<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <h1>Check if prime</h1>

    <b><?=$message ?></b>
    
    <form method='post'>
        <input type="number" name="number" placeholder='Enter number' value='<?=requestPost('number') ?>' > <br>
        <input type="submit" value="Submit"/>
    </form>
    
</body>
</html>