<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <h1>Register</h1>

    <b><?=$message ?></b>
    
    <form method='post'>
        <input type="text" name="first_name" placeholder='First name' value='<?=requestPost('first_name') ?>' > <br>
        <input type="text" name="last_name"  placeholder='Last name' value='<?=requestPost('last_name') ?>' ><br>
        <input type="email" name="email"  placeholder='Email' value='<?=requestPost('email') ?>' ><br>
        <input type="submit" value="Submit"/>
    </form>
    
</body>
</html>